module.exports=function(grunt){

	grunt.initConfig({
		watch:{
			jade:{
				files:["views/**"],
				options:{
					livereload:true
				}
			},
			js:{
				files:["public/js/**","module/**/*.js","schemas/**/*.js"],
				options:{
					livereload:true
				}
			}
		},
		nodemon:{
			dev:{
				options:{
					file:"app.js",
					args:[],
					ignoredFiles:["README.md","node_module/**",".DS_Store"],
					watchedExtensions:["js"],
					watchedFolders:["app","config"],
					debug:true,
					delayTime:1,
					env:{
						PORT:3000
					},
					cwd:__dirname
				}
			}
		},
		concurrent:{
			tasks:["nodemon","watch"],
			options:{
				logConcurrentOutput:true
			}
		}
	})

	grunt.loadNpmTasks("grunt-contrib-watch")
	grunt.loadNpmTasks("grunt-nodemon")
	grunt.loadNpmTasks("grunt-concurrent")

	grunt.option("force",false)
	grunt.registerTask("default",["concurrent"])
}